- src/api/post.js
- src/components/post/PostList.vue
- src/components/post/PostWrite.vue
- src/routes/index.js
> [feat]: 게시물 작성 기능 구현(#15)

- src/components/post/ThreadList.vue
> refactor: ThreadList 글 작성 버튼 삭제

- src/App.vue
- src/components/account/Signup.vue
- src/components/common/Footer.vue
- src/components/common/Header.vue
- src/components/common/Main.vue
- src/components/post/PostList.vue
- src/components/post/ThreadList.vue
- src/css/common.css
- src/css/reset.css
초기 디자인대로 Header, Footer, Main Page, SignUp page를 수정하였습니다.
> feat: Header, Footer 수정 / Main page, SignUp page css 수정 / 전체적인 폰트 수정(#20)

- src/api/post.js
- src/components/post/Post.vue
- src/components/post/PostList.vue
- src/routes/index.js
> [feat]: 게시물 단건 조회 기능 구현(#12)

- src/components/common/Header.vue
- src/components/common/Main.vue
> design: 메인페이지 디자인 일부 변경(#24)

- src/components/account/Signup.vue
> design: 회원가입 페이지 css 일부 수정(#27)

- src/components/account/Signin.vue
- src/css/common.css
> design: 로그인 페이지 디자인 변경(#23)

- src/components/common/Footer.vue
> design: Footer css 일부 수정(#30)

- src/components/post/PostList.vue
- src/components/post/PostWrite.vue
- src/components/post/ThreadList.vue
postwrite, postlist, threadlist 색감 전체적으로 통일
> feat: postwrite, postlist, threadlist 색감 전체적으로 통일(#42)

- src/components/account/Signin.vue
- src/components/account/Signup.vue
> design: 회원가입, 로그인페이지 스타일 적용(#52)

- src/components/account/MyComment.vue
- src/components/account/MyNotification.vue
- src/components/account/MyPosts.vue
- src/components/account/RecommendedComments.vue
- src/components/account/RecommendedPosts.vue
- src/components/account/RecommendedThreads.vue
- src/components/post/PostList.vue
- src/components/post/ThreadList.vue
> design: 반응형 웹 일부 페이지 수정(#54)

- src/components/common/Privacy.vue
- src/components/common/Terms.vue
> design: terms, privacy 페이지 반응형 웹 적용(#56)

- src/api/admin.js
- src/api/index.js
- src/api/post.js
- src/api/recommendation.js
- src/api/report.js
- src/components/admin/CommentReportList.vue
- src/components/post/Post.vue
> [feat]: 게시물 신고 기능 구현(#58)

- package-lock.json
- package.json
> [refactor]: package.json 수정(#65)

- src/components/common/Header.vue
- src/components/post/Post.vue
- src/components/post/PostList.vue
- src/components/post/PostWrite.vue
- src/components/post/Thread.vue
- src/components/post/ThreadList.vue
> [refactor]: 게시물, 쓰레드 이미지 업로드 및 의견 기능 수정(#67)

- src/components/post/Thread.vue
> [!HOTFIX]: thread 수정

- src/components/account/MyComment.vue
- src/components/account/MyNotification.vue
- src/components/account/MyPosts.vue
- src/components/account/RecommendedComments.vue
- src/components/account/RecommendedPosts.vue
- src/components/account/RecommendedThreads.vue
> fix: 뒤로가기가 되지 않는 이슈 해결(#9)

- src/App.vue
- src/components/common/Footer.vue
- src/components/post/Archive.vue
- src/components/post/ArchiveList.vue
- src/components/post/Post.vue
- src/components/post/PostList.vue
- src/components/post/Thread.vue
- src/components/post/ThreadList.vue
> refactor: 모바일 최적화(#61)

- src/components/post/Thread.vue
> [fix]: 게시물 신고 및 댓글 작성시 alert 추가(#75)

- src/components/post/ArchiveList.vue
- src/components/post/ThreadList.vue
쓰레드, 아카이브 카테고리 별, 추천순 등 정렬 기능 구현
> [feat]: 쓰레드, 아카이브 정렬 기능 구현(#77)
